### ISSUE TITLE
RTCC losing time.

### ISSUE THREAD

**Issue by Anobium** [lcgamboa/picsimlab#3] opened 2019-01-29 21:27 UTC
board 2.  The RTCC is losing time. Seconds are passing me by and the clock is not correct after only 60 secs.

Oh why?

**Comment by lcgamboa** [comment] 2019-01-31 00:47
The RTC is updated every 100ms by a wxTimer (https://docs.wxwidgets.org/3.0/classwx_timer.html). The accuracy of wxTimer varies according to OS, processing speed and system load. Theoretically the code as it is only would work without losing time on a real-time operating system, in this case linux and windows will always have a loss of time.
For simulation this loss of time is usually not critical.

**Comment by lcgamboa** [comment] 2019-02-02 01:58
When initialized the picsimlab the RTC updates itself with system time. At each overflow of the wxtimer the timer of the RTC is incremented by 100ms. The RTC is incremented 10 times per second or 600 times per minute. Considering that the wxtimer error is fixed in +2ms, every minute the accumulated error of the RTC will be of 1200ms! The RTC is not synchronized with the system clock. Your program is running normal and picsimlab RTC also within your limitations. It would be possible to program mechanisms to force the RTC to be synchronized with the system time, but would increase code complexity and overload the simulator further. As I said before, for simulation I do not see this need.

**Comment by Anobium** [comment] 2019-02-02 06:17
Thank you for the information. 

Recommended that you add an option to sync the RTCC with the system clock. Resync is important. We to show, in an educational context, that  the  clock is valid.

**Comment by lcgamboa** [comment] 2019-02-03 00:57
I will try to implement the RTC Resync in the next version as well.

**Comment by Anobium** [comment] 2019-02-06 13:37
OK.  Let me know and we can test.

**Comment by lcgamboa** [comment] 2019-02-11 19:21
What operating system did you use in the tests? I did some testing. Running on Linux the drift is 1 second every 3 minutes, using the emulator wine the drift in the windows version is 1 second every 5 minutes. Already running natively on windows 10 the drift is 1 second for every 10 seconds! So the problem is OS specific. I developed in Linux and test the version for windows with wine, so I never detected this problem before. I'm working on a way to fix the drift problem.

**Comment by Anobium** [comment] 2019-02-11 19:45
Windows 7. Native OS

**Comment by lcgamboa** [comment] 2019-02-12 00:39
Can you try this version: 
  https://www.dropbox.com/s/8i7uowhubn6vyhu/picsimlab_0_7_5_win64_setup_test.exe?dl=0
Apparently the problem has been fixed.
Inform me of the result on your computer

**Comment by Anobium** [comment] 2019-02-12 08:26
That works!

 

Excellent. I will leave running for a few hours.

**Comment by lcgamboa** [comment] 2019-02-13 17:50
Synchronization modifications have been added to the code in commit aa5bf5f . Can I consider the problem resolved?

**Comment by Anobium** [comment] 2019-02-13 17:58
Yes, Closed.  If you have removed the sync session window.

**Comment by lcgamboa** [comment] 2019-02-13 18:48
The console window is only active in the test versions, do not worry.

**Closed by lcgamboa** 2019-02-13 18:48 UTC
